apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: semtech-project
  namespace: argocd 
spec:
  project: default


  source:
    repoURL: 'https://github.com/tirjak/demo-project-k8s.git'
    targetRevision: main
    path: k8s # ArgoCD will look inside this folder for deployment.yaml
    directory:
      recurse: true
      exclude: argo_app.yaml

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default

  syncPolicy:
    automated:
      prune: true      # Automatically deletes resources from K8s if removed from Git
      selfHeal: true   # Automatically overwrites manual kubectl changes to match Git
    syncOptions:
      - CreateNamespace=true
